# Generated by Django 5.1.1 on 2024-09-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
