# Generated by Django 5.1.1 on 2024-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_marca_rename_categoria_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
